services:
  - type: web
    name: vapor-tg-bot
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: SCHEDULE_TIME
        value: "*/30 * * * *"
      - key: PORT
        value: 3000
    plan: free